name: "Mock-release JGiven"
on: [pull_request, push]

jobs:
  mock-release-jgiven:
    name: Mock-release JGiven
    runs-on: ubuntu-latest
    env:
      SONATYPE_PASSWORD: 'notARealPassword'
      SONATYPE_USERNAME: 'notARealUsername'
      GPG_PASSWORD: 'espalhando'
      GPG_KEY_ID: 'notARealKeyId@example.com'
      VERSION: '0.0.1-TEST'
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 11
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up openpgp signing keys
        run: |
          gpg --quick-gen-key --batch --passphrase "${GPG_PASSWORD}" "${GPG_KEY_ID}"
          gpg --list-keys
      - name: Set up mock server
        run: |
          wget https://repo1.maven.org/maven2/org/wiremock/wiremock-standalone/3.3.1/wiremock-standalone-3.3.1.jar
          wiremock=$(find ./ -name "wiremock-standalone-*.jar")
          java -jar ${wiremock} --port 7000 --verbose &
      - name: set an alternate version
        run: "source scripts/source_files/helper_functions.sh && updateAllVersionInformation ${VERSION}"
      - name: Attempt mock release
        run: >
          ./gradlew test publishMavenPublicationToMavenLocal publishMavenPublicationToMavenRepository 
          -PsigningKey="$(gpg --batch --pinentry-mode=loopback --yes --passphrase "${GPG_PASSWORD}" --armor --export-secret-key "${GPG_KEY_ID}")"
          -PsigningPassword="${GPG_PASSWORD}" -Ppublishing.releaseUrl=http://localhost:7000
      - name: Upload test results html files
        continue-on-error: true
        if: ${{failure()}}
        uses: actions/upload-artifact@v3.1.3
        with:
          name: test-report.zip
          path: /home/runner/work/JGiven/JGiven/*/build/reports/tests
          if-no-files-found: ignore

