name: "Mock-release JGiven"
on: [pull_request, push]

jobs:
  mock-release-jgiven:
    name: Mock-release JGiven
    runs-on: ubuntu-latest
    env:
      SONATYPE_PASSWORD: 'notARealPassword'
      SONATYPE_USERNAME: 'notARealUsername'
      GPG_PASSWORD: 'espalhando'
      GPG_KEY_ID: 'notARealKeyId@example.com'
      VERSION: '0.0.1-TEST'
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 11
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up openpgp signing keys
        run: |
          gpg --quick-gen-key --batch --passphrase "${GPG_PASSWORD}" "${GPG_KEY_ID}"

      - name: source release helpers
        run: >
          source scripts/source_files/helper_functions.sh && updateAllVersionInformation ${VERSION}
      - name: Attempt mock release
        run: >
          ./gradlew test signJGivenPluginPluginMarkerMavenPublication signMavenPublication signPluginMavenPublication publishToMavenLocal 
            "-PsigningKey=$(gpg --export-secret-key -a "${GPG_KEY_ID}" | sed -e '/^---.*/d' | tr -d '\n')" 
            "-PsigningPassword=${GPG_PASSWORD}" --debug
      - name: Upload test results html files
        continue-on-error: true
        if: ${{failure()}}
        uses: actions/upload-artifact@v3.1.3
        with:
          name: test-report.zip
          path: /home/runner/work/JGiven/JGiven/*/build/reports/tests
          if-no-files-found: ignore

